In [1]:
import numpy as np

In [9]:
## ques 1
# a
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)
# b
arr1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flattened_arr1 = arr1.flatten()
print(flattened_arr1)
# c
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print(np.array_equal(arr1, arr2)) 
#(element-wise)
print(arr1 == arr2) 
# d
x = np.array([1,2,3,4,5,1,2,1,1,1])
most_freq = np.bincount(x).argmax()
indices = np.where(x == most_freq)
print(most_freq, indices)
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
most_freq= np.bincount(y).argmax()
indices = np.where(y == most_freq)
print(most_freq, indices)
# e
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
total = np.sum(gfg)
row_sum = np.sum(gfg, axis=1)
col_sum = np.sum(gfg, axis=0)
print(total, row_sum, col_sum)
# f
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
diag_sum = np.trace(n_array)
eigen_values = np.linalg.eigvals(n_array)
eigen_values, eigen_vectors = np.linalg.eig(n_array)
inverse = np.linalg.inv(n_array)
det = np.linalg.det(n_array)
print(diag_sum, eigen_values, eigen_vectors, inverse, det)
# g
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
product1 = np.dot(p1, q1)
print("\nproduct:\n",product1)
cov1 = np.cov(p1.flatten(), q1.flatten())
print("\nCovariance:\n", cov1)
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2= np.array([[4, 5, 1], [6, 7, 2]])

[5 4 6 3 2 1]
[1 2 3 2 4 5 1 2 3]
True
[[ True  True]
 [ True  True]]
1 (array([0, 5, 7, 8, 9]),)
1 (array([0, 1, 2]),)
45 [[14]
 [16]
 [15]] [[20  9 16]]
176 [98.16835147 28.097044   49.73460452] [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]] [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]] 137180.0000000001

product:
 [[16 19]
 [26 31]]

Covariance:
 [[0.66666667 1.        ]
 [1.         1.66666667]]


In [7]:
product2 = np.dot(p2, q2)
print("\nproduct:\n",product2)
cov2 = np.cov(p2.flatten(), q2.flatten())
print("\nCovariance:\n", cov2)


product:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]

Covariance:
 [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [10]:
# h
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
inner = np.inner(x, y)
outer = np.outer(x.flatten(), y.flatten())
from itertools import product
cartesian = np.array(list(product(x.flatten(), y.flatten())))
print(inner, outer, cartesian)

[[17 52]
 [13 62]] [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]] [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [12]:
## ques 2
array = np.array([[1, -2, 3], [-4, 5, -6]])
abs_array = np.abs(array)
print(abs_array)
flat = array.flatten()
percentiles_flat = np.percentile(flat, [25, 50, 75])
print("Flat percentiles:", percentiles_flat)
percentiles_col = np.percentile(array, [25, 50, 75], axis=0)
print("Column percentiles:\n", percentiles_col)
percentiles_row = np.percentile(array, [25, 50, 75], axis=1)
print("Row percentiles:\n", percentiles_row)
print("Mean (flat):", np.mean(flat))
print("Median (flat):", np.median(flat))
print("Std Dev (flat):", np.std(flat))
print("Column mean:", np.mean(array, axis=0))
print("Column median:", np.median(array, axis=0))
print("Column std:", np.std(array, axis=0))
print("Row mean:", np.mean(array, axis=1))
print("Row median:", np.median(array, axis=1))
print("Row std:", np.std(array, axis=1))
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
print("Floor:", np.floor(a))        
print("Ceil:", np.ceil(a))          
print("Trunc:", np.trunc(a))         
print("Round:", np.round(a))        

[[1 2 3]
 [4 5 6]]
Flat percentiles: [-3.5 -0.5  2.5]
Column percentiles:
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Row percentiles:
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Mean (flat): -0.5
Median (flat): -0.5
Std Dev (flat): 3.8622100754188224
Column mean: [-1.5  1.5 -1.5]
Column median: [-1.5  1.5 -1.5]
Column std: [2.5 3.5 4.5]
Row mean: [ 0.66666667 -1.66666667]
Row median: [ 1. -4.]
Row std: [2.05480467 4.78423336]
Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceil: [-1. -1. -0.  1.  2.  2.  3.]
Trunc: [-1. -1. -0.  0.  1.  1.  3.]
Round: [-2. -2. -0.  0.  2.  2.  3.]


In [13]:
## ques 3
array = np.array([10, 52, 62, 16, 16, 54, 453])
sorted_array = np.sort(array)
print("Sorted:", sorted_array)
sorted_indices = np.argsort(array)
print("Indices of sorted:", sorted_indices)
print("Top 5 largest:", sorted_array[-5:])
print("Bottom 4 smallest:", sorted_array[:4]) 
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
int_elements = array[array == array.astype(int)]
print("Integer elements:", int_elements)
float_elements = array[array != array.astype(int)]
print("Float elements:", float_elements)


Sorted: [ 10  16  16  52  54  62 453]
Indices of sorted: [0 3 4 1 5 2 6]
Top 5 largest: [ 16  52  54  62 453]
Bottom 4 smallest: [10 16 16 52]
Integer elements: [1. 2. 3. 2.]
Float elements: [1.2 2.2]


In [15]:
## ques 4
from PIL import Image
import numpy as np

def img_to_array(path):
    img = Image.open(path)
    
    if img.mode == 'RGB':
        arr = np.array(img)
        np.savetxt("image_rgb.txt", arr.reshape(-1, 3), fmt='%d')
    elif img.mode == 'L':  # Grayscale
        arr = np.array(img)
        np.savetxt("image_gray.txt", arr, fmt='%d')
    else:
        raise ValueError("Unsupported image mode")

    print("Image saved as text.")


In [ ]:
# For grayscale:
gray_array = np.loadtxt("image_gray.txt")

# For RGB (reshaped back to 3 channels, assuming original shape is known, say (h, w, 3)):
rgb_flat = np.loadtxt("image_rgb.txt")
rgb_array = rgb_flat.reshape((height, width, 3))  # Replace with actual height and width
